---
Name: ContactPerson
---
Page:
  extensions:
    - ContactPerson\Extensions\PageExtension
PageController:
  extensions:
    - ContactPerson\Extensions\PageControllerExtension
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - ContactPerson\Extensions\SiteConfigExtension